server:
  port: 8200

spring:
  datasource:
    url: jdbc:mysql://rm-uf66q7416468877x8.mysql.rds.aliyuncs.com:3306/pig_house?autoReconnect=true&characterEncoding=utf8&useSSL=true
    username: root
    password: ss2ali_rds