spring:
  profiles:
    active: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    connectionTestQuery: "SELECT 1"
    validationQuery: "SELECT 1"
    testWhileIdle: true
    testOnBorrow: true
  jpa:
    hibernate:
      ddl-auto: update

